package rogo.sketch.core.debugger.ui;

public enum UiNodeType {
    PANEL,
    HEADER,
    TAB_BUTTON,
    TREE_GROUP,
    TREE_CONTROL,
    METRIC_CARD,
    BAR_CHART,
    MACRO_SECTION_HEADER,
    MACRO_CONSTANT_ROW,
    METRICS_LAYOUT_TOGGLE,
    CAPTURE_BUTTON,
    TOPBAR,
    TOPBAR_MENU_ITEM,
    POPUP_PANEL,
    POPUP_MENU_ITEM,
    WINDOW_TAB,
    LOG_COPY_BUTTON,
    DIAGNOSTIC_HEADER,
    DIAGNOSTIC_FILTER,
    DIAGNOSTIC_STATE,
    LOG_LINE,
    TOOLTIP
}
